name:                solsys-core
version:             0.1.0.0
github:              "dylan-thinnes/solsys-core"
license:             MIT
author:              "Dylan Thinnes"
maintainer:          "dylan.thinnes@protonmail.com"
copyright:           "2019 Dylan Thinnes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dylan-thinnes/solsys-core#readme>

dependencies:
- base >= 4.7 && < 5
- async
- random

library:
  source-dirs: src

executables:
  solsys-core-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - ./src/Primes/glue/msieve/glue.o
    - ./src/Primes/glue/primecount/glue.o
    - ./src/Primes/logint/li.o
    dependencies:
    - solsys-core
    extra-lib-dirs:
    - ./src/Primes/msieve
    - ./src/Primes/primecount
    extra-libraries:
    - gomp
    - stdc++
    - mpfr
    - gmp
    - msieve
    - primecount
