#!/bin/bash
if [ "$1" = "-h" ]; then
    echo "Usage: Compiles glue code for msieve, and makes msieve itself it it hasn't been yet."
    echo "    compile-msieve -h"
    echo "    compile-msieve -r"
    echo "Flags:"
    echo "    -h: Print help screen."
    echo "    -r: Recompile msieve library."
else
    cd ./Primes
    if [ ! -d "./msieve" ] || [ "$1" = "-r" ]; then
        if [ -d "./msieve" ]; then rm -r ./msieve; fi
        tar -xzf ./msieve153_src.tar.gz
        mv "./msieve-1.53" "./msieve"
        cd "./msieve"
        make all NO_ZLIB=1
        cd ".."
    fi
    cd glue/msieve
    gcc -Wall glue.c ../../msieve/libmsieve.a -lgmp -lm -lpthread -ldl -c -I../../msieve/include
    cd "../.."
    cd ".."
fi
